starting_commands: command_templates/sbatch_experiment.txt
experiments:
  Uniform.ParrotSmall:
    overrides:
      objective: 'lm'
      device: 0
      +disable_cache: True
      tracking:
        log_model: false
      model: 'lvwerra/codeparrot-small'
      ++num_proc: 4
      training:
        batch_size: 32
        gradient_accumulation_steps: 1
        learning_rate: 5e-4
        save_steps: 200
        eval_steps: 200
        logging_steps: 50
        ++max_steps: -1
    ablations:
      - DumpName:
          Negative:
            ++task.dump_name: negative
            ++task.answer_sorting: ascending
          Exceptions:
            ++task.dump_name: exceptions
          General:
            ++task.dump_name: general
          HighQual:
            ++task.dump_name: high_qual
            ++task.answer_sorting: descending
    steps:
      - name: PreTrain
        base: pretrain_config
        group: SO
        overrides:
          task: so
          ++task.max_samples: 27000
          ++task.max_val_samples: 250
          ++task.answers_per_sample: 1
      - name: FineTune
        base: greene_config
        group: MBPP
        overrides:
          task: mbpp
          ++is_checkpoint: True
          ++model_path: best_models/${..previous_step.save_name}
    command:
      file: command_templates/pretrain_then_finetune.txt
      kwargs:
        train_sbatch: train_single_gpu
        num_return_sequences: 100
