starting_commands: templates/commands/sbatch_experiment.txt
experiments:
  SeedTest:
    description: "Testing Different Seeds to view variance"
    overrides:
      ++device: 0
      is_checkpoint: false
      objective: lm
      ++evaluation:
        num_generate_per_step: 200
        remove_input_ids: True
        seq_per_sample: 200
    ablations:
      - Model:
          Neo125M:
            description: GPT Neo 125M
            overrides:
              ++model: 'EleutherAI/gpt-neo-125M'
            step_overrides:
              PreTrain:
                ++training.batch_size: 32
                ++training.gradient_accumulation_steps: 1
          ParrotSmall:
            description: CodeParrot Small
            overrides:
              ++model: 'lvwerra/codeparrot-small'
            step_overrides:
              PreTrain:
                ++training.batch_size: 32
                ++training.gradient_accumulation_steps: 1
                ++training.gradient_checkpointing: True
      - Seed:
          35:
            description: Seed Set to 35
            seed: 35
            numpy_seed: 35
            pytorch_seed: 35
          319:
            description: Seed Set to 319
            seed: 319
            numpy_seed: 319
            pytorch_seed: 319
          1999:
            description: Seed Set to 319
            seed: 319
            numpy_seed: 319
            pytorch_seed: 319
    steps:
      - name: PreTrain
        description: Finetune on the SO Data
        add_name: False
        base: pretrain
        group: SO
        overrides:
          ++task.buffer_size: 5000
          tracking:
            log_model: True
          is_checkpoint: False
          ++task.sequence_length: 1024
          task: so
      - name: FineTune
        add_name: False
        description: Finetune on the MBPP Data
        base: greene_config
        group: MBPP_SEED
        overrides:
          task: mbpp
          ++is_checkpoint: false
          ++model_path: null
          ++training:
            batch_size: 32
            gradient_accumulation_steps: 1
            learning_rate: 5e-5
          tracking:
            log_model: False
    command:
      file: templates/commands/evaluate_model.txt
      kwargs:
        train_sbatch: train_single_gpu
        pretrain_time: "12:00:00"
        use_cds: True
      fields:
        - model_path