# @package _global_
defaults:
  - _self_
  - override hydra/job_logging: custom

debug: False
project: "adversarial-code"
name: ???
group: ???
tracking:
  watch: "all"
  project: ${..project}
  log_model: false