# @package _global_
defaults:
  - _self_
  - override hydra/job_logging: custom

debug: False
project: so-code-gen
name: ???
group: ???
tracking:
  watch: "gradients"
  project: ${..project}
  log_model: false
  tags: [ ]