defaults:
  - _self_
  - task: ???
  - model_type: seq2seq
  - base_config

model_path: ???
is_checkpoint: true
split: ???
data_path: ???
project: "adversarial-code"

metrics:
  - exact-match
  - bleu

generation:
  max_length: 400
  do_sample: true
  temperature: 0.8
  top_k: 50
  top_p: 0.95
  num_return_sequences: 1
  min_length: 75

hydra:
  run:
    dir: outputs/evaluation/${task.name}