defaults:
  - _self_
  - task: ???

is_checkpoint: true
model_path: ???
seq_per_sample: 100
remove_input_ids: False
splits: ${task.eval_splits}
generation:
  max_length: 512
  num_return_sequences: 1
training:
  batch_size: 1

postprocessors:
  - strip: { }