defaults:
  - _self_
  - task: ???
  - objective: seq2seq
  - base_config

model_path: ???
is_checkpoint: true
split: ???
data_path: ???
project: "adversarial-code"

generate_steps: 1

metrics:
  - exact-match
  - bleu

training:
  eval_batch_size: 1

generation:
  max_length: 350
  do_sample: true
  temperature: 0.8
  top_k: 50
  top_p: 0.95
  num_return_sequences: 5
  min_length: 75

hydra:
  run:
    dir: outputs/${group}/${hydra.job.name}/${name}.${task.name}