defaults:
  - train_config@_global_
  - _self_

training:
  batch_size: 1
  learning_rate: 2e-5
  fp16: true
  num_train_epochs: 32
generation:
  num_return_sequences: 25
device: 0
tracking:
  log_model: true
