defaults:
  - base_config
  - task: ???
  - _self_
  - objective: seq2seq
  - override hydra/job_logging: custom

# Required Arguments
model: ???
model_path: null
is_checkpoint: false
project: "adversarial-code"


# General Arguments
data_path: data
device: cpu
seed: 1
numpy_seed: 2
pytorch_seed: 3

training:
  batch_size: 2
  output_dir: models
  learning_rate: 1e-5
  max_steps: 1000
  logging_steps: 50
  warmup_steps: 0.0
  warmup_ratio: 0.0
  weight_decay: 0.0
  gradient_accumulation_steps: 1
  eval_accumulation_steps: 1
  metric_for_best_model: 'loss'
  load_best_model_at_end: True
  save_total_limit: 5
  num_train_epochs: 10
  greater_is_better: False
  evaluation_strategy: epoch
  save_strategy: epoch
  group_by_length: True
  logging_first_step: True

hydra:
  run:
    dir: outputs/${group}/${hydra.job.name}/${name}.${task.name}

metrics:
  - exact-match
  - bleu
preprocessors:
  - add-prefix:
      prefix: "You are an expert Python programmer, and here is your task: "