defaults:
  - base_config
  - task: ???
  - training_args
  - _self_
  - objective: seq2seq
  - override hydra/job_logging: custom


training:
  train_batch_size: 2
  eval_batch_size: 2
  learning_rate: 1e-5
  weight_decay: 0.1
  save_epochs: 1
  logging_steps: 100
  grad_accumulation_steps: 1
  metric_for_best_model: "-loss"
  max_steps: 1000
  max_epochs: 4
  steps_per_epoch: 250

metrics:
  - exact-match
  - bleu
preprocessors:
  - add-prefix:
      prefix: "You are an expert Python programmer, and here is your task: "