defaults:
  - base_config
  - task: ???
  - training_args
  - _self_
  - model_type: seq2seq
  - override hydra/job_logging: custom


metrics:
  - exact-match
  - bleu
preprocessors:
  - add-prefix:
      prefix: "# You are an expert Python programmer, and here is your task: "