defaults:
  - base_config
  - task: ???
  - _self_
  - objective: seq2seq
  - override hydra/job_logging: custom

# Required Arguments
model: ???
model_path: null
is_checkpoint: false
project: "adversarial-code"


# General Arguments
data_path: data
device: cpu
seed: 1
numpy_seed: 2
pytorch_seed: 3

training:
  batch_size: 2
  output_dir: models
  group_by_length: True
  predict_with_generate: True
  evaluation_strategy: steps
  generation_max_length: 512
  learning_rate: 5e-5
  max_steps: 1000
  logging_steps: 500
  gradient_accumulation_steps: 1
  eval_accumulation_steps: 1
  metric_for_best_model: 'eval_loss'
  load_best_model_at_end: True
  save_steps: 500
  save_total_limit: 5

hydra:
  run:
    dir: outputs/${group}/${hydra.job.name}/${name}.${task.name}

metrics:
  - exact-match
  - bleu
preprocessors:
  - add-prefix:
      prefix: "You are an expert Python programmer, and here is your task: "