defaults:
  - base_config
  - task: ???
  - training_args
  - _self_
  - model_type: causal_lm
  - override hydra/job_logging: custom

task_kwargs:
  add_def_to_prompt: False

training:
  train_batch_size: 2
  eval_batch_size: 2
  learning_rate: 1e-5
  weight_decay: 0.1
  save_epochs: 1
  logging_steps: 100
  grad_accumulation_steps: 1
  metric_for_best_model: "-loss"
  max_steps: 1000
  max_epochs: 4
  steps_per_epoch: 250

data_args:
  seq_length: 512
  num_sequences: 5
  chars_per_token: 3.6
  streaming: False