defaults:
  - base_config
  - task: ???
  - _self_
  - objective: seq2seq
  - override hydra/job_logging: custom

# Required Arguments
model: ???
model_path: null
is_checkpoint: false
project: "adversarial-code"


# General Arguments
data_path: data
device: cpu
seed: 1
numpy_seed: 2
pytorch_seed: 3

# Training Arguments
training:
  train_batch_size: 2
  eval_batch_size: 2
  learning_rate: 1e-5
  weight_decay: 0.1
  save_epochs: 1
  logging_steps: 100
  grad_accumulation_steps: 1
  metric_for_best_model: "-loss"
  max_steps: 1000
  max_epochs: 10
  steps_per_epoch: 250
  checkpoints_to_save: 2

hydra:
  run:
    dir: outputs/${group}/${hydra.job.name}/${name}.${task.name}

metrics:
  - exact-match
  - bleu
preprocessors:
  - add-prefix:
      prefix: "You are an expert Python programmer, and here is your task: "