# @package _global_
defaults:
  - _self_
# Required Arguments
name: ???
group: ???
model: ???
model_path: null
is_checkpoint: false
project: "adversarial-code"


# General Arguments
data_path: data
device: cpu

seed: 1
numpy_seed: 2
pytorch_seed: 3

hydra:
  run:
    dir: outputs/${project}/${hydra.job.name}/${group}/${name}.${task.name}
