seed: 1
is_checkpoint: true
model_path: /home/gabe/Coding/springresearch/best_models/MBPP.CodeParrot150M
seq_per_sample: 100
remove_input_ids: true
splits:
- test
- validation
batch_size: 1
generation:
  max_new_tokens: 256
  do_sample: true
  temperature: 0.5
  top_p: 0.95
  top_k: 50
  num_return_sequences: 25
postprocessors:
- strip: {}
task:
  name: mbpp
  eval_splits:
  - test
  - validation
debug: false
project: adversarial-code
name: CodeParrot150M
group: MBPP
tracking: false
model: lvwerra/codeparrot-small
data_path: data
device: 0
numpy_seed: 2
pytorch_seed: 3
metrics:
- exact-match
- bleu
objective: lm
data_args:
  seq_length: 1024
disable_cache: true
preprocessors:
- add-prefix:
    prefix: 'You are an expert Python programmer, and here is your task: '
- add-suffix:
    suffix: '#Solution:

      '
    key: input_sequence
debug_num_samples: 10
split: []
run_id: 3eao1vs3
eval_run_name: CodeParrot150M-3eao1vs3
