debug: true
project: adversarial-code
name: debug
group: testing
tracking: false
task:
  name: mbpp
  paths:
    train: MBPP/train.jsonl
    validation: MBPP/validation.jsonl
model: patrickvonplaten/t5-tiny-random
model_path: null
is_checkpoint: false
data_path: data
device: 0
seed: 1
numpy_seed: 2
pytorch_seed: 3
training:
  train_batch_size: 2
  eval_batch_size: 2
  learning_rate: 1.0e-05
  weight_decay: 0.1
  save_epochs: 1
  logging_steps: 100
  grad_accumulation_steps: 1
  metric_for_best_model: -loss
  max_steps: 1000
  max_epochs: 10
  steps_per_epoch: 250
  checkpoints_to_save: 2
metrics:
- exact-match
- bleu
preprocessors:
- add-prefix:
    prefix: 'Prompt: '
objective: lm
data_args:
  seq_length: 512
  num_sequences: 5
  chars_per_token: 3.6
  streaming: false
